amcl: 

  ros__parameters: 

    use_sim_time: True 

    map_topic: /map 

    scan_topic: /scan 

    robot_base_frame: base_link 

 

bt_navigator: 

  ros__parameters: 

    use_sim_time: True 

    default_bt_xml_filename: "path/to/navigation_tree.xml" 

 

planner_server: 

  ros__parameters: 

    use_sim_time: True 

 

controller_server: 

  ros__parameters: 

    use_sim_time: True 

 

map_server: 

  ros__parameters: 

    use_sim_time: True 

    yaml_filename: "path/to/map.yaml" 

 

recovery_server: 

  ros__parameters: 

    use_sim_time: True 